/// Flutter icons NewsIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NewsIcons
///      fonts:
///       - asset: fonts/NewsIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class NewsIcons {
  NewsIcons._();

  static const _kFontFam = 'NewsIcons';
  static const String? _kFontPkg = null;

  static const IconData business = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health_care = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData science = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soccer_ball = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_dark = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
